name: Deploy to GitHub Pages

on:
  workflow_run:
    workflows: [ "Fetch News Daily" ]
    types:
      - completed
  push:
    branches:
      - main
    paths-ignore:
      - README.md
      - CODE_OF_CONDUCT.md
      - CONTRIBUTING.md
      - COURSE_TEMPLATE.mdx
      - LICENSE
      - .github/workflows/**
      - images/**

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build Web
        env:
          CHANGE_LOG: ${{ secrets.CHANGE_LOG }} # 将 Token 注入到环境变量
        run: npm run build

      - name: Update Build
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: Deploy to GitHub Pages
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4