name: Test Deploy

on:
  pull_request:
    branches:
      - main

jobs:
  test-deploy:
    name: Test Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: 安装依赖
        run: npm ci

      - name: 设置环境变量
        env:
          CHANGE_LOG: ${{ secrets.CHANGE_LOG }}
          DEPLOY_ENV: github
        run: echo "环境变量 GITHUB_TOKEN 已设置"

      - name: 测试构建网站
        env:
          CHANGE_LOG: ${{ secrets.CHANGE_LOG }} # 将环境变量注入到构建中
          DEPLOY_ENV: github
        run: npm run build
